### ISSUE TITLE
Refactoring pageOcr.py code

### ISSUE THREAD

**Issue by NishantWankhade** [NishantWankhade/PDF_to_OCR#1]
Tasks to be done :- 

- Create a function to which the arguments passed will be 
```bash
1) Path to the Images folder for each book
```
- Currently in the while loop I am giving the page number static, however that should be according to the number of images in the images folder. 

_**The Path to the image folder will be like :- "{path to book}/images/"**_
_**The Path to output where the ocred text will be saved will be like :- "{path to book}/ocr_by_bhashini/"**_

**Comment by NishantWankhade** [comment]
@KoushikTeja Please confirm once you understand the task well.

**Comment by KoushikTeja** [comment]
[https://github.com/NishantWankhade/PDF_to_OCR/commit/cb07fa1033e6e6509189e402ac4d62a3097778b6](url)
